# specify NodeJs base image with tag: 12.18.0-alpine3.9
FROM node:12.18.0-alpine3.9

EXPOSE 3000

# craate app directory
RUN mkdir -p /app
WORKDIR /app

# copy package.json with dependencies
COPY package.json /app/package.json

ARG http_proxy
ARG https_proxy
ARG no_proxy

# copy folder
COPY .npmrc /app/.npmrc
COPY package-lock.json /app/package-lock.json

# install all depencies
RUN http_proxy=${http_proxy} https_proxy=${https_proxy} no_proxy=${no_proxy} npm --verbose install

RUN npm --verbose install http-proxy-middleware --save
# RUN npm --verbose install

COPY public /app/public
COPY src /app/src
# COPY node_modules /app/node_modules

# build project
RUN npm build

# run the todo app
CMD [ "npm", "start" ]