# specify NodeJs base image with tag: 12.18.0-alpine3.9
FROM node:12.18.2-buster-slim
RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    net-tools \
    netcat \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

# craate app directory
RUN mkdir -p /app
WORKDIR /app

# copy package.json with dependencies
COPY package.json package-lock.json /app/

ARG http_proxy
ARG https_proxy
ARG no_proxy

# copy folder
COPY .npmrc /app/.npmrc
COPY package-lock.json /app/package-lock.json

# install all depencies
RUN npm --verbose install

COPY public /app/public
COPY src /app/src
# COPY node_modules /app/node_modules

# # build project
# RUN npm build

# # run the todo app
# CMD [ "npm", "start" ]