# specify NodeJs base image with tag: 12.18.0-alpine3.9
FROM node:12.18.0-alpine3.9

EXPOSE 9000

# craate app directory
RUN mkdir -p /app
WORKDIR /app

# copy package.json with dependencies
COPY package.json /app/package.json

# copy folder
COPY bin /app/bin
COPY public /app/public
COPY routes /app/routes
COPY views /app/views
COPY .npmrc /app/.npmrc
COPY app.js /app/app.js

# install all depencies
RUN npm install

# run the todo app
CMD [ "npm", "start" ]