# specify NodeJs base image with tag: 12.18.0-alpine3.9
FROM node:12.18.2-buster-slim
RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    net-tools \
    netcat \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# copy package.json with dependencies
COPY .npmrc /app/.npmrc
COPY package.json package-lock.json /app/
# install all depencies
RUN npm install --verbose
ENV PATH=$PATH:/app/node_modules/.bin
# copy folder
COPY bin /app/bin
COPY public /app/public
COPY routes /app/routes
COPY views /app/views

COPY app.js /app/app.js

EXPOSE 9000
# run the todo app
CMD [ "npm", "start" ]